%YAML 1.2
---
name: '128x10'
gpu: 0

dataset: 
  num_chunks: 500000
  train_ratio: 0.90
  # For separated test and train data.
  #input_train: '/path/to/chunks/*/draw/'
  #input_test: '/path/to/chunks/*/draw/'
  # For a one-shot run with all data in one directory.
  input: 'F:/lczero/data/'

training: 
    warmup_steps: 250
    swa: true
    swa_output: true
    swa_max_n: 10
    swa_steps: 25
    mask_legal_moves: true
    renorm: true
    renorm_max_r: 1.0
    renorm_max_d: 0.0
    q_ratio: 0.20
    max_grad_norm: 2
    batch_size: 4096
    num_batch_splits: 4
    test_steps: 125
    num_test_positions: 40000
    train_avg_report_steps: 50
    total_steps: 1000
    # checkpoint_steps: 10000
    shuffle_size: 500000
    lr_values:
        - 0.15
        - 0.15
    lr_boundaries:
        - 120
    policy_loss_weight: 1.0
    value_loss_weight: 0.5
    path: 'F:/lczero/networks'
    workers: 1

model:
  filters: 128
  residual_blocks: 10
  se_ratio: 4
...
